name: Validate JSON structure

on:
  pull_request:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v3

    - name: Navigate to backend directory
      run: cd backend; pwd

    - name: install JQ package
      run: sudo apt-get update -y && sudo apt-get install jq --yes

    - name: Validate JSON files
      run: |
        for file in $(find . -type f -name "*.json"); do
          echo "Validating $file"
          jq empty $file || exit 1
        done

    - name: Complete
      run: echo "JSON is valid"
